### ISSUE TITLE
option to not open duplicated file

### ISSUE THREAD

**Issue by nancym** [robole/file-bunny#1]
When I duplicate a file, it's almost always because I want a backup of the file and I do not want to view or edit this duplicate file. It would be great if there were an option to not open a duplicate file.

Thanks for this cool extension! 🐰 🐇

**Comment by robole** [comment]
hi @nancym 

thanks for the feedback. im glad you like the extension.

it sounds like a common enough scenario to want to duplicate a file without opening it. a core reason for making the extension was to reduce the number of hops to do stuff like this, hence the name! 

initially, i wanted to keep the numbers of commands to a minimum and see how I found using them. I wanted to see if i bumped into something i felt I needed but was missing and add them on that basis to keep it lean. i rarely find myself duplicating files, so this is not a pain point me! however, i am happy to add something like this if enough people feel the pain.

there is a case for making alternative commands for the existing commands that work on active files (`delete active file` ..etc) also. i created a new issue for this #2 .You can give a 👍 to the issue and i will consider adding it if there is more interest, and i have time! atm, my time for this is very limited.
